name: Beta
on:
  push:
    branches:
      - develop
  jobs:
    bump-version:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Bump version'
        run: npm version prerelease --preid="beta"
