name: CI
on:
  push

jobs:
  run-tests:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
      - name: Run tests
        run: npm run test
        env:
          CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}

  build-package:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop'
    needs: run-tests
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
      - name: Build package
        run: npm run build
      - uses: actions/upload-artifact@v1
        with:
          name: dist
          path: dist
  build-docs:
    runs-on: ubuntu-latest
    needs: build-package
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Setup git
        run: |
            git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
            git config --global user.name "$GITHUB_ACTOR"
            git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
      - name: Build docs
        run: npm run docs:ci
      - name: Create .nojekyll
        run: touch docs/.nojekyll
      - name: Stage changes
        run: git add -A
      - name: Commit changes
        run: git commit -m "Updated docs"
      - name: Push
        run: git push
  publish-beta:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    needs: build-docs
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Setup git
        run: |
            git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
            git config --global user.name "$GITHUB_ACTOR"
            git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
      - name: Pull changes
        run: git pull
      - name: Bump version
        run: npm version prerelease --preid="beta"
      - name: Push
        run: git push
      - name: Push tags
        run: git push --tags
      - name: Download artifacts
        uses: actions/download-artifact@v1
        with:
          name: dist
      - name: Publish to registry
        run: |
          npm config set //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
  publish-release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs: build-docs
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Setup git
        run: |
            git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
            git config --global user.name "$GITHUB_ACTOR"
            git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
      - name: Pull changes
        run: git pull
      - name: Bump version
        run: npm version from-git
      - name: Push
        run: git push
      - name: Push tags
        run: git push --tags
      - name: Download artifacts
        uses: actions/download-artifact@v1
        with:
          name: dist
      - name: Publish to registry
        run: |
          npm config set //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
